# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sexy_scopes}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Samuel Lebeau"]
  s.date = %q{2011-09-11}
  s.description = %q{Small DSL to create ActiveRecord attribute predicates without writing SQL.}
  s.email = %q{samuel.lebeau@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/sexy_scopes.rb",
    "rails/init.rb",
    "sexy_scopes.gemspec",
    "spec/sexy_scopes_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/samleb/sexy_scopes}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Small DSL to create ActiveRecord attribute predicates without writing SQL.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.9"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.0"])
      s.add_development_dependency(%q<sqlite3>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.1"])
      s.add_development_dependency(%q<rcov>, ["~> 0.9"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3.0"])
      s.add_dependency(%q<rake>, ["~> 0.9"])
      s.add_dependency(%q<jeweler>, ["~> 1.0"])
      s.add_dependency(%q<sqlite3>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, ["~> 2.1"])
      s.add_dependency(%q<rcov>, ["~> 0.9"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3.0"])
    s.add_dependency(%q<rake>, ["~> 0.9"])
    s.add_dependency(%q<jeweler>, ["~> 1.0"])
    s.add_dependency(%q<sqlite3>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, ["~> 2.1"])
    s.add_dependency(%q<rcov>, ["~> 0.9"])
  end
end

